version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing something"

  pre_build:
    commands:
      - echo "we are in the pre build phase"

  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - echo "<h1>Congratulations</h1>" > index.html
      - echo "File list:"
      - ls -l
      - echo "File content:"
      - cat index.html
      - grep -Fq "Congratulations" index.html

  post_build:
    commands:
      - echo "we are in the post build phase"

artifacts:
  files:
    - '**/*'



            
